{"name": "Авторизаиця с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1745527537384, "stop": 1745527538118}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1745527538118, "stop": 1745527538441}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1745527538441, "stop": 1745527538474}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1745527537384, "stop": 1745527538474, "uuid": "6667f578-fa7e-42b2-8d30-984a8461a9d3", "historyId": "3230c37a4ddf37e226b736e144aaba65", "testCaseId": "89a909a1ca222b871b75e39c89c26fa1", "fullName": "tests.test_login#test_login_failure", "labels": [{"name": "feature", "value": "Авторизаци"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "Elshad27"}, {"name": "thread", "value": "5408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}